name: Auto Rebase PRs on Main Changes (Excluding Drafts, `no-rebase` Label, and `main` Branch)

on:
  push:
    branches:
      - main  # Déclenché lorsqu'il y a un push sur la branche main

permissions:
  contents: write  # Autorisations d'écriture pour le token

jobs:
  list-and-rebase-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List Open PRs (Excluding Drafts, `no-rebase` Label, and Main Branch)
      run: |
        # Liste des PRs ouvertes qui ne sont pas en draft et n'ont pas le label `no-rebase`
        pr_branches=$(gh pr list --state open --json headRefName,draft,labels --jq '.[] | select(.isDraft == false) | select([.labels[].name] | index("no-rebase") | not) | select(.headRefName != "main") | .headRefName')

        for branch in $pr_branches; do
          echo "Rebasing $branch"
          git checkout $branch
          git fetch origin main
          git rebase origin/main
          git push --force-with-lease
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
